#!/usr/bin/env python3
"""Compose each enabled agent's global rules file from the read-only base rules
(/agent-rules/AGENTS.md) plus the AGENTS.md fragments of the plugins ENABLED in
this container.

Why a generated file instead of the old symlink: /agent-rules is a read-only
bind mount (usually an external rules repo), so a plugin's usage guidance cannot
be appended there. up.sh runs this once at `up`; an interactive-shell hook
(src/rules-compose.bashrc) re-runs it, so the base stays as live as the mount —
the fragments themselves are image-fixed (baked under /opt/plugins).

Enabled-only: the image bakes EVERY plugin's fragment, but a container is told
how to use only the plugins its manifest turned on. up.sh writes that list (the
derived PLUGINS var) to the enabled-file, the single source of truth both the
`up`-time and shell-start composes read.

The workspace contract (/workspace/AGENTS.md, installed by up.sh) is appended
after the fragments, so every agent with a rules_file reads it through the same
channel as the base rules. Byte-identical when no enabled plugin ships a
fragment AND the contract is absent: the base is written through verbatim.

Stdlib only (matches wire_plugins.py). Writes are atomic (tmp + rename), which
also swaps a pre-existing symlink target for a regular file WITHOUT ever writing
through it into the read-only mount — os.replace re-points the directory entry,
never the link's target. Runtime code here cannot parse agents/*/agent.yml, so
the build renders enabled agent descriptors to /usr/local/lib/djinn/agents-index.tsv
once and this module reads target rules files from that index.
"""

import argparse
import os
import sys
from pathlib import Path

# Defaults resolve to the paths up.sh and the image establish; the bashrc hook
# invokes this with no arguments and relies on every one of them.
DEFAULT_BASE = "/agent-rules/AGENTS.md"
DEFAULT_PLUGINS_ROOT = "/opt/plugins"
DEFAULT_ENABLED_FILE = "/home/coder/.config/djinn/enabled-plugins"
DEFAULT_INDEX = "/usr/local/lib/djinn/agents-index.tsv"
DEFAULT_WORKSPACE = "/workspace/AGENTS.md"

FRAGMENT_NAME = "AGENTS.md"
GEN_NOTICE = (
    "<!-- Generated by djinn (src/compose_rules.py): base rules + the "
    "AGENTS.md fragments of the plugins enabled in this container. Edit "
    "plugins/<name>/AGENTS.md, not this file. -->"
)
SECTION_HEADING = "# Plugin tools enabled in this container"
WORKSPACE_NOTICE = (
    "<!-- Generated by djinn (src/compose_rules.py): the workspace contract, "
    "copied from /workspace/AGENTS.md so every harness reads it. Edit "
    "docs/workspace.AGENTS.md in brassbottle, not this file. -->"
)


def _read_text(path):
    """Read with newline translation OFF so a no-fragment compose round-trips
    the base byte-for-byte (paired with _write_atomic's newline='')."""
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def _write_atomic(path, text):
    """tmp + rename in the target's own directory. os.replace is atomic and
    replaces a symlink entry with the regular file (never writes the target)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / (path.name + ".tmp")
    with open(tmp, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    os.replace(tmp, path)


def read_enabled(enabled_file):
    """The enabled-plugin names, whitespace-split, or None if the file is ABSENT.

    Absent ≠ empty. up.sh always writes this file (empty when a container has no
    plugins), so an EMPTY file authoritatively means "no plugins" → base-only,
    whereas an ABSENT file means "unknown" — the caller must NOT downgrade a
    previously-good composed file to base-only on a guess, so it skips the write
    (like a missing base). Prevents a vanished enabled-file from silently
    stripping the plugin section on the next shell-hook recompose."""
    path = Path(enabled_file)
    if not path.is_file():
        return None
    return path.read_text(encoding="utf-8").split()


def _safe_name(name):
    """A plugin name is a single path segment. up.sh feeds manifest-validated
    names ([A-Za-z0-9_-]), but this module also reads an on-disk enabled-file
    standalone, so reject anything that could escape the plugins root (a '..'
    or a separator) before it reaches a filesystem read — defense in depth."""
    return name and name not in (".", "..") and "/" not in name and "\\" not in name


def load_fragments(plugins_root, names):
    """(name, text) for each enabled plugin that ships a non-empty AGENTS.md,
    in the given order (manifest order — deterministic, author-controllable).
    A plugin without a fragment, or with an empty one, is silently skipped."""
    root = Path(plugins_root)
    fragments = []
    for name in names:
        if not _safe_name(name):
            continue
        frag = root / name / FRAGMENT_NAME
        if not frag.is_file():
            continue
        text = frag.read_text(encoding="utf-8")
        if not text.strip():
            continue
        fragments.append((name, text))
    return fragments


def compose(base_text, fragments, workspace_text=None):
    """base_text, then a fenced 'enabled tools' section carrying each fragment,
    then the workspace contract (the same text for every harness). No fragments
    and no workspace text → base_text is returned UNCHANGED (byte-identical
    guarantee). An empty or whitespace-only workspace text counts as absent."""
    has_workspace = bool(workspace_text and workspace_text.strip())
    if not fragments and not has_workspace:
        return base_text
    parts = [base_text.rstrip("\n"), ""]
    if fragments:
        parts += [GEN_NOTICE, SECTION_HEADING, ""]
        for _name, text in fragments:
            parts.append(text.strip("\n"))
            parts.append("")
    if has_workspace:
        parts += [WORKSPACE_NOTICE, workspace_text.strip("\n"), ""]
    return "\n".join(parts).rstrip("\n") + "\n"


def load_workspace(path):
    """The workspace contract text, or None when the file is absent (an older
    container that has not been re-`up`ed, or a compose before the copy)."""
    p = Path(path)
    if not p.is_file():
        return None
    return p.read_text(encoding="utf-8")


def default_targets(home, index):
    path = Path(index)
    if not path.is_file():
        return None
    targets = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        cols = raw.split("\t")
        if len(cols) < 3:
            print(
                f"  ⚠ malformed agents-index row (expected at least 3 tab fields): {raw}",
                file=sys.stderr,
            )
            continue
        rules_file = cols[2].strip()
        if not rules_file:
            continue
        targets.append(Path(home) / rules_file)
    return targets


def run(base, plugins_root, enabled_file, targets=None, index=DEFAULT_INDEX, announce=False,
        workspace=DEFAULT_WORKSPACE):
    """Compose the file and write every target. Returns 0 on success. Three
    warn-and-skip guards (return 1) keep the shell hook from clobbering a
    previously-good file with a downgrade: a missing base (mount briefly gone),
    an ABSENT enabled-file (unknown plugin set — empty would be authoritative
    'no plugins', but absent must not become a base-only guess), and an ABSENT
    agents index when default targets are in use (unknown target set, same
    downgrade risk). up.sh/image setup writes all three on the normal path."""
    base_path = Path(base)
    if not base_path.is_file():
        print(f"  ⚠ base rules {base_path} not found — leaving agent rules files as-is",
              file=sys.stderr)
        return 1

    if targets is None:
        targets = default_targets(_home(), index)
        if targets is None:
            print(f"  ⚠ agents index {index} absent — leaving agent rules files as-is",
                  file=sys.stderr)
            return 1

    names = read_enabled(enabled_file)
    if names is None:
        print(f"  ⚠ enabled-plugins file {enabled_file} absent — leaving agent rules files as-is",
              file=sys.stderr)
        return 1

    base_text = _read_text(base_path)
    fragments = load_fragments(plugins_root, names)
    workspace_text = load_workspace(workspace)
    has_workspace = bool(workspace_text and workspace_text.strip())
    if not has_workspace:
        print(f"  ⚠ workspace contract {workspace} absent or empty — composing without it",
              file=sys.stderr)
    composed = compose(base_text, fragments, workspace_text)

    for target in targets:
        _write_atomic(Path(target), composed)

    if announce:
        parts = [n for n, _ in fragments]
        if has_workspace:
            parts.append("workspace contract")
        if parts:
            print("  ✓ agent rules composed (base + " + ", ".join(parts) + ")")
        else:
            print("  ✓ agent rules composed (base only — no enabled plugin ships an AGENTS.md, "
                  f"no {workspace})")
    return 0


def _home():
    """The exec user's real home (passwd), matching wire_plugins._home so a
    future ENV HOME=… in the image can't misdirect the targets."""
    try:
        import pwd
        return Path(pwd.getpwuid(os.getuid()).pw_dir)
    except (ImportError, KeyError):
        return Path(os.environ.get("HOME", "/home/coder"))


def main(argv):
    ap = argparse.ArgumentParser(description="Compose agent rules = base + enabled-plugin fragments.")
    ap.add_argument("--base", default=DEFAULT_BASE)
    ap.add_argument("--plugins-root", default=DEFAULT_PLUGINS_ROOT)
    ap.add_argument("--enabled-file", default=DEFAULT_ENABLED_FILE)
    ap.add_argument("--workspace", default=DEFAULT_WORKSPACE,
                    help="workspace contract appended to every target (absent → skipped)")
    ap.add_argument("--index", default=DEFAULT_INDEX,
                    help="Agent descriptor index TSV. Used only when --target is not passed.")
    ap.add_argument("--target", action="append", dest="targets",
                    help="Output file (repeatable). Defaults to <home>/<rules_file> from --index.")
    ap.add_argument("--announce", action="store_true", help="Print a ✓ summary line (up.sh uses this; the shell hook does not).")
    args = ap.parse_args(argv)

    targets = args.targets if args.targets else None
    return run(args.base, args.plugins_root, args.enabled_file, targets=targets,
               index=args.index, announce=args.announce, workspace=args.workspace)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
